{"text": "2024-03-13 06:24:21 | INFO    | __main__:stash:131 | run - {'image': '20231121', 'version': '0.10.1.post2', 'role': 'EpicPlayer', 'headless': True}\n", "record": {"elapsed": {"repr": "0:00:01.761401", "seconds": 1.761401}, "exception": null, "extra": {"image": "20231121", "version": "0.10.1.post2", "role": "EpicPlayer", "headless": true}, "file": {"name": "claim.py", "path": "/home/runner/work/epic-free/epic-free/epic/src/claim.py"}, "function": "stash", "level": {"icon": "ℹ️", "name": "INFO", "no": 20}, "line": 131, "message": "run", "module": "claim", "name": "__main__", "process": {"id": 4156, "name": "MainProcess"}, "thread": {"id": 139713908079488, "name": "MainThread"}, "time": {"repr": "2024-03-13 06:24:21.283455+08:00", "timestamp": 1710282261.283455}}}
{"text": "2024-03-13 06:24:30 | INFO    | __main__:claim_epic_games:97 | Try to flush cookie - {'task': 'claim_epic_games'}\n", "record": {"elapsed": {"repr": "0:00:10.614703", "seconds": 10.614703}, "exception": null, "extra": {"task": "claim_epic_games"}, "file": {"name": "claim.py", "path": "/home/runner/work/epic-free/epic-free/epic/src/claim.py"}, "function": "claim_epic_games", "level": {"icon": "ℹ️", "name": "INFO", "no": 20}, "line": 97, "message": "Try to flush cookie", "module": "claim", "name": "__main__", "process": {"id": 4156, "name": "MainProcess"}, "thread": {"id": 139713908079488, "name": "MainThread"}, "time": {"repr": "2024-03-13 06:24:30.136757+08:00", "timestamp": 1710282270.136757}}}
{"text": "2024-03-13 06:24:32 | SUCCESS    | epic_games.agent:_login:253 | login - {'result': 'Successfully refreshed tokens'}\n", "record": {"elapsed": {"repr": "0:00:12.631284", "seconds": 12.631284}, "exception": null, "extra": {"result": "Successfully refreshed tokens"}, "file": {"name": "agent.py", "path": "/home/runner/work/epic-free/epic-free/epic/src/epic_games/agent.py"}, "function": "_login", "level": {"icon": "✅", "name": "SUCCESS", "no": 25}, "line": 253, "message": "login", "module": "agent", "name": "epic_games.agent", "process": {"id": 4156, "name": "MainProcess"}, "thread": {"id": 139713908079488, "name": "MainThread"}, "time": {"repr": "2024-03-13 06:24:32.153338+08:00", "timestamp": 1710282272.153338}}}
{"text": "2024-03-13 06:24:39 | SUCCESS    | epic_games.agent:flush_token:280 | flush_token - {'path': PosixPath('/home/runner/work/epic-free/epic-free/epic/user_data_dir/epic-games@1075199251/ctx_cookie.json')}\n", "record": {"elapsed": {"repr": "0:00:19.849891", "seconds": 19.849891}, "exception": null, "extra": {"path": "/home/runner/work/epic-free/epic-free/epic/user_data_dir/epic-games@1075199251/ctx_cookie.json"}, "file": {"name": "agent.py", "path": "/home/runner/work/epic-free/epic-free/epic/src/epic_games/agent.py"}, "function": "flush_token", "level": {"icon": "✅", "name": "SUCCESS", "no": 25}, "line": 280, "message": "flush_token", "module": "agent", "name": "epic_games.agent", "process": {"id": 4156, "name": "MainProcess"}, "thread": {"id": 139713908079488, "name": "MainThread"}, "time": {"repr": "2024-03-13 06:24:39.371945+08:00", "timestamp": 1710282279.371945}}}
{"text": "2024-03-13 06:24:39 | WARNING    | epic_games.agent:get_order_history:467 | Failed to get order history, cookie may have expired - {}\n", "record": {"elapsed": {"repr": "0:00:19.967896", "seconds": 19.967896}, "exception": null, "extra": {}, "file": {"name": "agent.py", "path": "/home/runner/work/epic-free/epic-free/epic/src/epic_games/agent.py"}, "function": "get_order_history", "level": {"icon": "⚠️", "name": "WARNING", "no": 30}, "line": 467, "message": "Failed to get order history, cookie may have expired", "module": "agent", "name": "epic_games.agent", "process": {"id": 4156, "name": "MainProcess"}, "thread": {"id": 139713908079488, "name": "MainThread"}, "time": {"repr": "2024-03-13 06:24:39.489950+08:00", "timestamp": 1710282279.48995}}}
{"text": "2024-03-13 06:24:44 | ERROR    | __main__:run:158 | An error has been caught in function 'run', process 'MainProcess' (4156), thread 'MainThread' (139713908079488): - {}\nTraceback (most recent call last):\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/httpx/_transports/default.py\", line 69, in map_httpcore_exceptions\n    yield\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/httpx/_transports/default.py\", line 233, in handle_request\n    resp = self._pool.handle_request(req)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py\", line 216, in handle_request\n    raise exc from None\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py\", line 196, in handle_request\n    response = connection.handle_request(\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/httpcore/_sync/connection.py\", line 101, in handle_request\n    return self._connection.handle_request(request)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/httpcore/_sync/http11.py\", line 143, in handle_request\n    raise exc\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/httpcore/_sync/http11.py\", line 113, in handle_request\n    ) = self._receive_response_headers(**kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/httpcore/_sync/http11.py\", line 186, in _receive_response_headers\n    event = self._receive_event(timeout=timeout)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/httpcore/_sync/http11.py\", line 224, in _receive_event\n    data = self._network_stream.read(\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/httpcore/_backends/sync.py\", line 124, in read\n    with map_exceptions(exc_map):\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/contextlib.py\", line 153, in __exit__\n    self.gen.throw(typ, value, traceback)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/httpcore/_exceptions.py\", line 14, in map_exceptions\n    raise to_exc(exc) from exc\nhttpcore.ReadTimeout: The read operation timed out\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/home/runner/work/epic-free/epic-free/epic/src/claim.py\", line 162, in <module>\n    asyncio.run(run())\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/asyncio/runners.py\", line 44, in run\n    return loop.run_until_complete(main)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/asyncio/base_events.py\", line 636, in run_until_complete\n    self.run_forever()\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/asyncio/base_events.py\", line 603, in run_forever\n    self._run_once()\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/asyncio/base_events.py\", line 1909, in _run_once\n    handle._run()\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/asyncio/events.py\", line 80, in _run\n    self._context.run(self._callback, *self._args)\n> File \"/home/runner/work/epic-free/epic-free/epic/src/claim.py\", line 158, in run\n    await agent.stash()\n  File \"/home/runner/work/epic-free/epic-free/epic/src/claim.py\", line 151, in stash\n    await self.claim_epic_games(context)\n  File \"/home/runner/work/epic-free/epic-free/epic/src/claim.py\", line 106, in claim_epic_games\n    self.create_tasks()\n  File \"/home/runner/work/epic-free/epic-free/epic/src/claim.py\", line 64, in create_tasks\n    self._pros = get_promotions()\n  File \"/home/runner/work/epic-free/epic-free/epic/src/epic_games/agent.py\", line 411, in get_promotions\n    resp = httpx.get(URL_PROMOTIONS, params=params)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/httpx/_api.py\", line 198, in get\n    return request(\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/httpx/_api.py\", line 106, in request\n    return client.request(\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/httpx/_client.py\", line 827, in request\n    return self.send(request, auth=auth, follow_redirects=follow_redirects)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/httpx/_client.py\", line 914, in send\n    response = self._send_handling_auth(\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/httpx/_client.py\", line 942, in _send_handling_auth\n    response = self._send_handling_redirects(\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/httpx/_client.py\", line 979, in _send_handling_redirects\n    response = self._send_single_request(request)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/httpx/_client.py\", line 1015, in _send_single_request\n    response = transport.handle_request(request)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/httpx/_transports/default.py\", line 232, in handle_request\n    with map_httpcore_exceptions():\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/contextlib.py\", line 153, in __exit__\n    self.gen.throw(typ, value, traceback)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/httpx/_transports/default.py\", line 86, in map_httpcore_exceptions\n    raise mapped_exc(message) from exc\nhttpx.ReadTimeout: The read operation timed out\n", "record": {"elapsed": {"repr": "0:00:25.370779", "seconds": 25.370779}, "exception": {"type": "ReadTimeout", "value": "The read operation timed out", "traceback": true}, "extra": {}, "file": {"name": "claim.py", "path": "/home/runner/work/epic-free/epic-free/epic/src/claim.py"}, "function": "run", "level": {"icon": "❌", "name": "ERROR", "no": 40}, "line": 158, "message": "An error has been caught in function 'run', process 'MainProcess' (4156), thread 'MainThread' (139713908079488):", "module": "claim", "name": "__main__", "process": {"id": 4156, "name": "MainProcess"}, "thread": {"id": 139713908079488, "name": "MainThread"}, "time": {"repr": "2024-03-13 06:24:44.892833+08:00", "timestamp": 1710282284.892833}}}
